### ISSUE TITLE
Rename to `nixpkgs-vet`

### ISSUE THREAD

**Issue by philiptaron** [NixOS/nixpkgs-vet#100]
The purpose of this tool is to [vet](https://en.wiktionary.org/wiki/vet#Verb) nixpkgs.

There are now, as of late August 2024, 28 specific errors that this tool checks for. Some of them have to do with [RFC 140](https://github.com/NixOS/rfcs/blob/master/rfcs/0140-simple-package-paths.md) and the `pkgs/by-name` directory, but many of them are good hygiene for packages in general that _happen_ to be checked as part of this migration.

As the migration completes, this tool will continue to have a place as a leveraged way to vet the contents of packages that are contributed to Nixpkgs.

We should therefore rename it to the short, punchy name of `nixpkgs-vet`.

**Comment by willbush** [comment]
Oh think I misunderstood what you meant by https://github.com/NixOS/nixpkgs-check-by-name/issues/99#issuecomment-2311162464. Want me to make a PR here to rename?

**Comment by philiptaron** [comment]
Yes please! Then:

1. An org owner can rename this repository
2. We can make a release
3. We can update nixpkgs

**Comment by philiptaron** [comment]
All right, once we do a release, update nixpkgs, and rename the team in the org, we'll be done with this.

**Comment by infinisil** [comment]
Team is renamed: https://github.com/orgs/NixOS/teams/nixpkgs-vet :)

**Comment by infinisil** [comment]
Release can be done by just updating `Cargo.{toml,lock}`

**Comment by philiptaron** [comment]
With #106, I'm calling this done.

**Comment by infinisil** [comment]
Oh nice catch, changed it to "Tool to vet (check) Nixpkgs, including its pkgs/by-name directory" now
