### ISSUE TITLE
nixpkgs-vet wants to move packages with uppercase names to pkgs/by-name

### ISSUE THREAD

**Issue by pluiedev** [NixOS/nixpkgs-vet#133]
Ditto (see https://github.com/NixOS/nixpkgs/actions/runs/12161429913/job/33916017215)

This issue is sort of similar to #107 and we really need to be more careful and only select packages that fit the naming criteria outlined by RFC 140:

> Check the following using CI:
> - `pkgs/by-name` must only contain subdirectories of the form `${shard}/${name}`, called _package directories_.
> - The `name`'s of package directories must be unique when lowercased
> - `name` is a string only consisting of the ASCII characters `a-z`, `A-Z`, `0-9`, `-` or `_`.
> - `shard` is the lowercased first two letters of `name`, expressed in Nix: `shard = toLower (substring 0 2 name)`.
> - Each package directory must contain a `package.nix` file and may contain arbitrary other files.

**Comment by pluiedev** [comment]
NVM, I misread the RFC 😓

**Comment by infinisil** [comment]
Not sure I get what you mean, can you be more specific?
